//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsentedPetsV._2._0.Vista.PerfilesRol.Usuario
{


    public partial class ListarPedido
    {
    }
}
